package repositories.businesserrors;

public enum CreateOfferCodes {
    SERVER_ERROR,
    UNAUTHORIZED,
    OFFER_OVERCOMED,
    AUCTION_NOT_FOUND,
    AUCTION_FINISHED,
    AUCTION_BLOCKED,
    EARLY_OFFER,
    MINIMUM_BID_NOT_FULFILLED,
    BASE_PRICE_NOT_FULLFILLED,
    AUCTION_OWNER,
    VALIDATION_ERROR,
    UNKNOWN
}
